/*SELECCIONO LA BASE DE DATOS*/
USE sifadmin;

/*CREO LA TABLA*/
CREATE TABLE `entidades_admninistradoras` (
	`Codigo_Entidad_Administradora` VARCHAR(6) NOT NULL,
	`Entidad_Administradora` VARCHAR(10) NULL DEFAULT NULL,
	`Nit_EA` VARCHAR(20) NULL DEFAULT NULL,
	`Direccion_EA` VARCHAR(100) NULL DEFAULT NULL,
	`Telefonos_EA` VARCHAR(50) NULL DEFAULT NULL,
	`Departamento` VARCHAR(2) NULL DEFAULT NULL,
	`Municipio` VARCHAR(5) NULL DEFAULT NULL,
	`CorreoEntidd` VARCHAR(255) NULL DEFAULT NULL,
	`Soat` BINARY(50) NOT NULL,
	`Activo` TINYINT(3) UNSIGNED NOT NULL,
	`TipoCuenta` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
	`RipsDigVer` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
	`CodigoATC` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
	`LongAutorizacion` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
	`DireccionRadicado` VARCHAR(100) NULL DEFAULT NULL,
	`Regimen` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
	`OtrosDatos` VARCHAR(255) NULL DEFAULT NULL,
	`Reporte256` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
	`ReqAnexo2` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
	`LonOtro` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
	`DigVer` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
	`RipsRN` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
	`CodigoInterno` VARCHAR(6) NULL DEFAULT NULL,
	PRIMARY KEY (`Codigo_Entidad_Administradora`)
);

/*HAGO MODIFICACIONES A LA TABLA*/

/*SCRIPTS CORRESPONDIENTES A LA TABLA*/