/*SELECCIONO LA BASE DE DATOS*/
USE sifadmin;

/*CREO LA TABLA*/
CREATE TABLE `Ips` (
	Control TINYINT UNSIGNED NOT NULL,
	Codigo VARCHAR(12) NULL,
	Nombre_IPS VARCHAR(60) NULL,
	Tipo_Identificacion VARCHAR(2) NULL,
	Nit VARCHAR(20) NULL,
	DigitoVerificacion TINYINT UNSIGNED NULL,
	Direccion VARCHAR(40) NULL,
	Telefonos VARCHAR(30) NULL,
	Responsable_Rips VARCHAR(50) NULL,
	Dian VARCHAR(50) NULL,
	PieCuenta VARCHAR(255) NULL,
	DepartamentoIPS VARCHAR(2) NULL,
	MunicipioIPS VARCHAR(5) NULL,
	NoFactura INT NULL,
	Indicativo VARCHAR(3) NULL,
	Logo VARCHAR(30) NULL,
	Email VARCHAR(50) NULL,
	INTernoFactura INT NULL,
	DelegadoSOAT VARCHAR(50) NULL,
	CuentaC INT NULL,
	INTernoRips VARCHAR(20) NULL,
	Remisiones TINYINT UNSIGNED NULL,
	HistoriaClinica TINYINT UNSIGNED NULL,
	HistoriaOdont TINYINT UNSIGNED NULL,
	CentPrede TINYINT UNSIGNED NULL,
	CHAsist TINYINT UNSIGNED NULL,
	CHAdJ TINYINT UNSIGNED NULL,
	CHAdM TINYINT UNSIGNED NULL,
	CHEmb TINYINT UNSIGNED NULL,
	CHPf TINYINT UNSIGNED NULL,
	CHCd TINYINT UNSIGNED NULL,
	CHHip TINYINT UNSIGNED NULL,
	LiqAut TINYINT UNSIGNED NULL,
	DiasEstProl TINYINT UNSIGNED NULL,
	Nivel TINYINT UNSIGNED NULL,
	Anexo2Obl TINYINT UNSIGNED NULL,
	TelSIAU VARCHAR(35) NULL,
	Fosyga TINYINT UNSIGNED NULL,
	DianDesde VARCHAR(20) NULL,
	DianHasta VARCHAR(20) NULL,
	DianFecha datetime NULL,
	FacAdi TINYINT UNSIGNED NULL,
	Gerente VARCHAR(100) NULL,
	Firma VARCHAR(30) NULL,
	CedulaGerente INT NULL,
	ExpedidaGerente VARCHAR(50) NULL,
	JefePresupuesto VARCHAR(100) NULL,
	SubgerenteAdministrativo VARCHAR(100) NULL,
	SubgerenteAdministrativoFirma VARCHAR(30) NULL,
	RecursosHumanos VARCHAR(100) NULL,
	FirmaRecursosHumanos VARCHAR(30) NULL,
	CajaCF VARCHAR(6) NULL,
	RevisorFiscal VARCHAR(100) NULL,
	RevisorFiscalFirma VARCHAR(30) NULL,
	RutaRadicados VARCHAR(50) NULL,
	INTOrdenProc VARCHAR(20) NULL,
	Prefijo VARCHAR(3) NULL,
	FechaS DATETIME NULL,
	HoraCita TINYINT UNSIGNED NULL,
	DianVigencia VARCHAR(10) NULL,
	PRIMARY KEY (`Control`),
	FOREIGN KEY (DepartamentoIPS) REFERENCES Departamentos(Codigo_Departamento) ,
	FOREIGN KEY (MunicipioIPS) REFERENCES Municipios(Codigo_Completo) 
);

/*HAGO MODIFICACIONES A LA TABLA*/
ALTER TABLE Ips ALTER Nivel SET DEFAULT 0;
ALTER TABLE Ips ALTER Anexo2Obl SET DEFAULT 0;
ALTER TABLE Ips ALTER Fosyga SET DEFAULT 100;
ALTER TABLE Ips ALTER Prefijo SET DEFAULT 0;
ALTER TABLE Ips ALTER HoraCita SET DEFAULT 0;

/*SCRIPTS CORRESPONDIENTES A LA TABLA*/